# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\rcontainerclaw\"1\n\x0bTaskRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"/\n\nTaskStatus\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x0f\x41\x63tivityRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"U\n\rActivityEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\nrisk_score\x18\x04 \x01(\x02\x32\xa6\x01\n\x0c\x41gentService\x12\x44\n\x0b\x45xecuteTask\x12\x1a.containerclaw.TaskRequest\x1a\x19.containerclaw.TaskStatus\x12P\n\x0eStreamActivity\x12\x1e.containerclaw.ActivityRequest\x1a\x1c.containerclaw.ActivityEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=79
  _globals['_TASKSTATUS']._serialized_start=81
  _globals['_TASKSTATUS']._serialized_end=128
  _globals['_ACTIVITYREQUEST']._serialized_start=130
  _globals['_ACTIVITYREQUEST']._serialized_end=167
  _globals['_ACTIVITYEVENT']._serialized_start=169
  _globals['_ACTIVITYEVENT']._serialized_end=254
  _globals['_AGENTSERVICE']._serialized_start=257
  _globals['_AGENTSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
