# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/containerclaw.AgentService/ExecuteTask',
                request_serializer=agent__pb2.TaskRequest.SerializeToString,
                response_deserializer=agent__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.StreamActivity = channel.unary_stream(
                '/containerclaw.AgentService/StreamActivity',
                request_serializer=agent__pb2.ActivityRequest.SerializeToString,
                response_deserializer=agent__pb2.ActivityEvent.FromString,
                _registered_method=True)
        self.ListWorkspace = channel.unary_unary(
                '/containerclaw.AgentService/ListWorkspace',
                request_serializer=agent__pb2.WorkspaceRequest.SerializeToString,
                response_deserializer=agent__pb2.WorkspaceResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/containerclaw.AgentService/ReadFile',
                request_serializer=agent__pb2.FileRequest.SerializeToString,
                response_deserializer=agent__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DiffFile = channel.unary_unary(
                '/containerclaw.AgentService/DiffFile',
                request_serializer=agent__pb2.DiffRequest.SerializeToString,
                response_deserializer=agent__pb2.DiffResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/containerclaw.AgentService/GetHistory',
                request_serializer=agent__pb2.ActivityRequest.SerializeToString,
                response_deserializer=agent__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetBoard = channel.unary_unary(
                '/containerclaw.AgentService/GetBoard',
                request_serializer=agent__pb2.ActivityRequest.SerializeToString,
                response_deserializer=agent__pb2.BoardResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/containerclaw.AgentService/ListSessions',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.SessionListResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/containerclaw.AgentService/CreateSession',
                request_serializer=agent__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=agent__pb2.SessionEntry.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Start a new task on the agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActivity(self, request, context):
        """Stream activity logs and thought states to the UI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspace(self, request, context):
        """List files in the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Read a single file from the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffFile(self, request, context):
        """Get diff data for a file (vs git HEAD)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Get chat history from Fluss
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoard(self, request, context):
        """Get project board items (W-2: Fluss-backed)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Phase 13: Session Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__pb2.TaskRequest.FromString,
                    response_serializer=agent__pb2.TaskStatus.SerializeToString,
            ),
            'StreamActivity': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamActivity,
                    request_deserializer=agent__pb2.ActivityRequest.FromString,
                    response_serializer=agent__pb2.ActivityEvent.SerializeToString,
            ),
            'ListWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspace,
                    request_deserializer=agent__pb2.WorkspaceRequest.FromString,
                    response_serializer=agent__pb2.WorkspaceResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=agent__pb2.FileRequest.FromString,
                    response_serializer=agent__pb2.FileResponse.SerializeToString,
            ),
            'DiffFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffFile,
                    request_deserializer=agent__pb2.DiffRequest.FromString,
                    response_serializer=agent__pb2.DiffResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=agent__pb2.ActivityRequest.FromString,
                    response_serializer=agent__pb2.HistoryResponse.SerializeToString,
            ),
            'GetBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoard,
                    request_deserializer=agent__pb2.ActivityRequest.FromString,
                    response_serializer=agent__pb2.BoardResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.SessionListResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=agent__pb2.CreateSessionRequest.FromString,
                    response_serializer=agent__pb2.SessionEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'containerclaw.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('containerclaw.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/ExecuteTask',
            agent__pb2.TaskRequest.SerializeToString,
            agent__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/containerclaw.AgentService/StreamActivity',
            agent__pb2.ActivityRequest.SerializeToString,
            agent__pb2.ActivityEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/ListWorkspace',
            agent__pb2.WorkspaceRequest.SerializeToString,
            agent__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/ReadFile',
            agent__pb2.FileRequest.SerializeToString,
            agent__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiffFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/DiffFile',
            agent__pb2.DiffRequest.SerializeToString,
            agent__pb2.DiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/GetHistory',
            agent__pb2.ActivityRequest.SerializeToString,
            agent__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/GetBoard',
            agent__pb2.ActivityRequest.SerializeToString,
            agent__pb2.BoardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/ListSessions',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.SessionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/containerclaw.AgentService/CreateSession',
            agent__pb2.CreateSessionRequest.SerializeToString,
            agent__pb2.SessionEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
